Add check backup directory else create to DOCKERME_CONTAINRS_BACKUP

diff --git a/dockerme b/dockerme
--- a/dockerme
+++ b/dockerme
@@ -802,7 +802,7 @@ DOCKERME_CONTAINERS_BACKUP(){
 	PROGRESS_STICKY=yes
 	PROGRESS_WIDTH=100
 	progress_max_lines=1
-	PROGRESS_NUMBER_OF_STEPS=${1:-7}
+	PROGRESS_NUMBER_OF_STEPS=${1:-8}
 	DOCKERME_PROGRESS
 	for i in $(seq $PROGRESS_NUMBER_OF_STEPS); do
 		if [[ $i -eq 1 ]]; then
@@ -824,6 +824,22 @@ DOCKERME_CONTAINERS_BACKUP(){
 				exit
 			fi
 		elif [[ $i -eq 5 ]]; then
+			. /$DOCKERME_CONFIG
+			if [ -d $HOME_PATH_DIRECTORY/$DOMAINE_NAME/backup ]; then
+				MESSAGES="CHECK BACKUP DIRECTORY $HOME_PATH_DIRECTORY/$DOMAINE_NAME/backup" STATUS=1 STATUS_MSG="OK" DOCKERME_LOG_WRITE
+				echo $d ": [OK] : CHECK BACKUP DIRECTORY $HOME_PATH_DIRECTORY/$DOMAINE_NAME/backup " >> $DOCKERME_LOG.log
+			else
+				mkdir $HOME_PATH_DIRECTORY/$DOMAINE_NAME/backup
+				if [[ $? -eq 0 ]]; then
+					MESSAGES="CREATE BACKUP DIRECTORY $HOME_PATH_DIRECTORY/$DOMAINE_NAME/backup" STATUS=1 STATUS_MSG="OK" DOCKERME_LOG_WRITE
+					echo $d ": [OK] : CEATE BACKUP DIRECTORY $HOME_PATH_DIRECTORY/$DOMAINE_NAME/backup " >> $DOCKERME_LOG.log
+				else
+					MESSAGES="CREATING BACKUP DIRECTORY $HOME_PATH_DIRECTORY/$DOMAINE_NAME/backup" STATUS=0 STATUS_MSG="FAIL" DOCKERME_LOG_WRITE
+					echo $d ": [FAIL] : CEATING BACKUP DIRECTORY $HOME_PATH_DIRECTORY/$DOMAINE_NAME/backup " >> $DOCKERME_LOG.log
+					exit
+				fi
+			fi
+		elif [[ $i -eq 6 ]]; then
 			mv $D.zip $HOME_PATH_DIRECTORY/$DOMAINE_NAME/backup/$D.zip 1>/dev/null 2>&1;
 			if [[ $? -eq 0 ]]; then
 				MESSAGES="MOVE ARCHIVE FILE $D.zip TO BACKUP REPOSITORY $HOME_PATH_DIRECTORY/$DOMAINE_NAME/backup/$D.zip" STATUS=1 STATUS_MSG="OK" DOCKERME_LOG_WRITE
@@ -833,9 +849,9 @@ DOCKERME_CONTAINERS_BACKUP(){
 				echo $d ": [FAIL] : MOVING ARCHIVE FILE $D.zip TO BACKUP REPOSITORY $HOME_PATH_DIRECTORY/$DOMAINE_NAME/backup/$D.zip" >> $DOCKERME_LOG.log
 				exit
 			fi
-		elif [[ $i -eq 6 ]]; then
-			DOMAINE_NAME=$DOMAINE_NAME DOCKERME_CONTAINERS_START
 		elif [[ $i -eq 7 ]]; then
+			DOMAINE_NAME=$DOMAINE_NAME DOCKERME_CONTAINERS_START
+		elif [[ $i -eq 8 ]]; then
 			MESSAGES="BACKUP $DOMAINE_NAME" STATUS=1 STATUS_MSG="COMPLETED" DOCKERME_LOG_WRITE
 			echo $d ": [COMPLETED] : BACKUP $DOMAINE_NAME" >> $DOCKERME_LOG.log
 		fi
