add DOCKERME_CONTAINERS_BACKUP

diff --git a/dockerme b/dockerme
--- a/dockerme
+++ b/dockerme
@@ -798,14 +798,57 @@ DOCKERME_CONTAINERS_REMOVE(){
 		progress_step
 	done
 }
+DOCKERME_CONTAINERS_BACKUP(){
+	PROGRESS_STICKY=yes
+	PROGRESS_WIDTH=100
+	progress_max_lines=1
+	PROGRESS_NUMBER_OF_STEPS=${1:-6}
+	DOCKERME_PROGRESS
+	for i in $(seq $PROGRESS_NUMBER_OF_STEPS); do
+		if [[ $i -eq 1 ]]; then
+			MESSAGES="BACKUP $DOMAINE_NAME" STATUS=1 STATUS_MSG="INITIALIZING" DOCKERME_LOG_WRITE
+			echo $d `users` ": [INITIALIZING] : DOCKERME UNINSTALL" >> $DOCKERME_LOG.log
+		elif [[ $i -eq 2 ]]; then
+			DOCKERME_IF_WEBSITE_DIRECTORY_NOT_EXIST
+			MESSAGES="CHECK DOMAINE_NAME=$DOMAINE_NAME" STATUS=1 STATUS_MSG="OK" DOCKERME_LOG_WRITE
+		elif [[ $i -eq 3 ]]; then
+			DOMAINE_NAME=$DOMAINE_NAME DOCKERME_CONTAINERS_STOP
+		elif [[ $i -eq 4 ]]; then
+			zip -r $D.zip $HOME_PATH_DIRECTORY/$DOMAINE_NAME -x '*backup/*' 1>/dev/null 2>&1;
+			if [[ $? -eq 0 ]]; then
+				MESSAGES="CREATE ARCHIVE FILE $D.zip" STATUS=1 STATUS_MSG="OK" DOCKERME_LOG_WRITE
+				echo $d `users` ": [OK] : CREATE ARCHIVE FILE $D.zip" >> $DOCKERME_LOG.log
+			else
+				MESSAGES="CREATING ARCHIVE FILE $D.zip" STATUS=0 STATUS_MSG="FAIL" DOCKERME_LOG_WRITE
+				echo $d `users` ": [FAIL] : CREATING ARCHIVE FILE $D.zip" >> $DOCKERME_LOG.log
+				exit
+			fi
+		elif [[ $i -eq 5 ]]; then
+			mv $D.zip $HOME_PATH_DIRECTORY/$DOMAINE_NAME/backup/$D.zip 1>/dev/null 2>&1;
+			if [[ $? -eq 0 ]]; then
+				MESSAGES="MOVE ARCHIVE FILE $D.zip TO BACKUP REPOSITORY $HOME_PATH_DIRECTORY/$DOMAINE_NAME/backup/$D.zip" STATUS=1 STATUS_MSG="OK" DOCKERME_LOG_WRITE
+				echo $d `users` ": [OK] : MOVING ARCHIVE FILE $D.zip TO BACKUP REPOSITORY $HOME_PATH_DIRECTORY/$DOMAINE_NAME/backup/$D.zip" >> $DOCKERME_LOG.log
+			else
+				MESSAGES="MOVING ARCHIVE FILE $D.zip TO BACKUP REPOSITORY $HOME_PATH_DIRECTORY/$DOMAINE_NAME/backup/$D.zip" STATUS=0 STATUS_MSG="FAIL" DOCKERME_LOG_WRITE
+				echo $d `users` ": [FAIL] : MOVING ARCHIVE FILE $D.zip TO BACKUP REPOSITORY $HOME_PATH_DIRECTORY/$DOMAINE_NAME/backup/$D.zip" >> $DOCKERME_LOG.log
+				exit
+			fi
+		elif [[ $i -eq 6 ]]; then
+			MESSAGES="BACKUP $DOMAINE_NAME" STATUS=1 STATUS_MSG="COMPLETED" DOCKERME_LOG_WRITE
+			echo $d `users` ": [COMPLETED] : BACKUP $DOMAINE_NAME" >> $DOCKERME_LOG.log
+		fi
+	  progress_step
+	done 
+}
 DOCKERME_HEADER
 DOCKERME_GLOBAL_VARS
 #DOCKERME_YML_LIST
 #DOCKERME_YML_UPDATE
 #DOCKERME_LOG_TRUNCATE
-DOCKERME_INSTALL
+#DOCKERME_INSTALL
 #DOCKERME_UNINSTALL
 #DOMAINE_NAME=ayoub.tn YML=wordpress4.9.5-php7.0-apache_mysql5.7.22 DOCKERME_CONTAINERS_CREATE
 #DOMAINE_NAME=ayoub.tn DOCKERME_CONTAINERS_REMOVE
 #DOMAINE_NAME=ayoub.tn DOCKERME_CONTAINERS_START
 #DOMAINE_NAME=ayoub.tn DOCKERME_CONTAINERS_STOP
+#DOMAINE_NAME=ayoub.tn DOCKERME_CONTAINERS_BACKUP
