add delete old backup function

diff --git a/dockerme b/dockerme
--- a/dockerme
+++ b/dockerme
@@ -850,6 +850,16 @@ DOCKERME_CONTAINERS_BACKUP(){
 		elif [[ $i -eq 7 ]]; then
 			DOMAINE_NAME=$DOMAINE_NAME DOCKERME_CONTAINERS_START
 		elif [[ $i -eq 8 ]]; then
+			find $HOME_PATH_DIRECTORY/$DOMAINE_NAME/* -mtime +7 -exec rm {} \; 1>/dev/null 2>&1;
+			if [[ $? -eq 0 ]]; then
+				MESSAGES="DELETE OLD BACKUPS" STATUS=1 STATUS_MSG="OK" DOCKERME_LOG_WRITE
+				echo $d ": [OK] : DELETE OLD BACKUPS" >> $DOCKERME_LOG.log
+			else
+				MESSAGES="DELETING OLD BACKUPS" STATUS=1 STATUS_MSG="WARNING" DOCKERME_LOG_WRITE
+				echo $d ": [FAIL] : DELETING OLD BACKUPS" >> $DOCKERME_LOG.log
+				exit
+			fi
+		elif [[ $i -eq 9 ]]; then
 			MESSAGES="BACKUP $DOMAINE_NAME" STATUS=1 STATUS_MSG="COMPLETED" DOCKERME_LOG_WRITE
 			echo $d ": [COMPLETED] : BACKUP $DOMAINE_NAME" >> $DOCKERME_LOG.log
 		fi
