isolate bakups and add DOCKERME_CONTAINERS_BACKUP_DELETE_OLD

diff --git a/dockerme b/dockerme
--- a/dockerme
+++ b/dockerme
@@ -8,6 +8,7 @@ DOCKERME_SHOW_HELP(){
 	echo "    dockerme -yml --update                      update yml files"
 	echo "    dockerme -c domainename.tld yml             create dockers based on docker-compose from yml with specific domaine"
 	echo "    dockerme -b domainename.tld                 create backup from specific domainename.tld"
+	echo "    dockerme -b domainename.tld --older ndays   create backup from specific domainename.tld and delete backups older than ndays"
 	echo "    dockerme -b domainename.tld --list          list backup files for specific domainename.tld"
 	#echo "    dockerme -b -s domainename.tld              create backup from specific domainename.tld with a crontab"
 	#echo "    dockerme -b -s domainename.tld --list       list a crontab file from specific domainename.tld"
@@ -850,13 +851,74 @@ DOCKERME_CONTAINERS_BACKUP(){
 		elif [[ $i -eq 7 ]]; then
 			DOMAINE_NAME=$DOMAINE_NAME DOCKERME_CONTAINERS_START
 		elif [[ $i -eq 8 ]]; then
-			DOMAINE_NAME=$DOMAINE_NAME OLDER_THAN_N_DAYS="7" DOCKERME_DELETE_OLD_BACKUP
-		elif [[ $i -eq 9 ]]; then
 			MESSAGES="BACKUP $DOMAINE_NAME" STATUS=1 STATUS_MSG="COMPLETED" DOCKERME_LOG_WRITE
 			echo $d ": [COMPLETED] : BACKUP $DOMAINE_NAME" >> $DOCKERME_LOG.log
 		fi
 	  progress_step
 	done 
+}
+DOCKERME_CONTAINERS_BACKUP_DELETE_OLD(){
+	PROGRESS_STICKY=yes
+	PROGRESS_WIDTH=100
+	progress_max_lines=1
+	PROGRESS_NUMBER_OF_STEPS=${1:-9}
+	DOCKERME_PROGRESS
+	for i in $(seq $PROGRESS_NUMBER_OF_STEPS); do
+		if [[ $i -eq 1 ]]; then
+			MESSAGES="BACKUP $DOMAINE_NAME" STATUS=1 STATUS_MSG="INITIALIZING" DOCKERME_LOG_WRITE
+			echo $d ": [INITIALIZING] : DOCKERME UNINSTALL" >> $DOCKERME_LOG.log
+		elif [[ $i -eq 2 ]]; then
+			DOCKERME_IF_WEBSITE_DIRECTORY_NOT_EXIST
+			MESSAGES="CHECK DOMAINE_NAME=$DOMAINE_NAME" STATUS=1 STATUS_MSG="OK" DOCKERME_LOG_WRITE
+		elif [[ $i -eq 3 ]]; then
+			DOMAINE_NAME=$DOMAINE_NAME DOCKERME_CONTAINERS_STOP
+		elif [[ $i -eq 4 ]]; then
+			cd $HOME_PATH_DIRECTORY/$DOMAINE_NAME
+			zip -r $D.zip * -x '*backup/*' -x '*.yml*' 1>/dev/null 2>&1;
+			if [[ $? -eq 0 ]]; then
+				MESSAGES="CREATE ARCHIVE FILE $D.zip" STATUS=1 STATUS_MSG="OK" DOCKERME_LOG_WRITE
+				echo $d ": [OK] : CREATE ARCHIVE FILE $D.zip" >> $DOCKERME_LOG.log
+			else
+				MESSAGES="CREATING ARCHIVE FILE $D.zip" STATUS=0 STATUS_MSG="FAIL" DOCKERME_LOG_WRITE
+				echo $d ": [FAIL] : CREATING ARCHIVE FILE $D.zip" >> $DOCKERME_LOG.log
+				exit
+			fi
+		elif [[ $i -eq 5 ]]; then
+			. /$DOCKERME_CONFIG
+			if [ -d $HOME_PATH_DIRECTORY/$DOMAINE_NAME/backup ]; then
+				MESSAGES="CHECK BACKUP DIRECTORY $HOME_PATH_DIRECTORY/$DOMAINE_NAME/backup" STATUS=1 STATUS_MSG="OK" DOCKERME_LOG_WRITE
+				echo $d ": [OK] : CHECK BACKUP DIRECTORY $HOME_PATH_DIRECTORY/$DOMAINE_NAME/backup " >> $DOCKERME_LOG.log
+			else
+				mkdir $HOME_PATH_DIRECTORY/$DOMAINE_NAME/backup
+				if [[ $? -eq 0 ]]; then
+					MESSAGES="CREATE BACKUP DIRECTORY $HOME_PATH_DIRECTORY/$DOMAINE_NAME/backup" STATUS=1 STATUS_MSG="OK" DOCKERME_LOG_WRITE
+					echo $d ": [OK] : CEATE BACKUP DIRECTORY $HOME_PATH_DIRECTORY/$DOMAINE_NAME/backup " >> $DOCKERME_LOG.log
+				else
+					MESSAGES="CREATING BACKUP DIRECTORY $HOME_PATH_DIRECTORY/$DOMAINE_NAME/backup" STATUS=0 STATUS_MSG="FAIL" DOCKERME_LOG_WRITE
+					echo $d ": [FAIL] : CEATING BACKUP DIRECTORY $HOME_PATH_DIRECTORY/$DOMAINE_NAME/backup " >> $DOCKERME_LOG.log
+					exit
+				fi
+			fi
+		elif [[ $i -eq 6 ]]; then
+			mv $D.zip $HOME_PATH_DIRECTORY/$DOMAINE_NAME/backup/$D.zip 1>/dev/null 2>&1;
+			if [[ $? -eq 0 ]]; then
+				MESSAGES="MOVE ARCHIVE FILE $D.zip TO BACKUP REPOSITORY $HOME_PATH_DIRECTORY/$DOMAINE_NAME/backup/$D.zip" STATUS=1 STATUS_MSG="OK" DOCKERME_LOG_WRITE
+				echo $d ": [OK] : MOVING ARCHIVE FILE $D.zip TO BACKUP REPOSITORY $HOME_PATH_DIRECTORY/$DOMAINE_NAME/backup/$D.zip" >> $DOCKERME_LOG.log
+			else
+				MESSAGES="MOVING ARCHIVE FILE $D.zip TO BACKUP REPOSITORY $HOME_PATH_DIRECTORY/$DOMAINE_NAME/backup/$D.zip" STATUS=0 STATUS_MSG="FAIL" DOCKERME_LOG_WRITE
+				echo $d ": [FAIL] : MOVING ARCHIVE FILE $D.zip TO BACKUP REPOSITORY $HOME_PATH_DIRECTORY/$DOMAINE_NAME/backup/$D.zip" >> $DOCKERME_LOG.log
+				exit
+			fi
+		elif [[ $i -eq 7 ]]; then
+			DOMAINE_NAME=$DOMAINE_NAME DOCKERME_CONTAINERS_START
+		elif [[ $i -eq 8 ]]; then
+			DOMAINE_NAME=$DOMAINE_NAME OLDER_THAN_N_DAYS=$OLDER_THAN_N_DAYS DOCKERME_DELETE_OLD_BACKUP
+		elif [[ $i -eq 9 ]]; then
+			MESSAGES="BACKUP $DOMAINE_NAME" STATUS=1 STATUS_MSG="COMPLETED" DOCKERME_LOG_WRITE
+			echo $d ": [COMPLETED] : BACKUP $DOMAINE_NAME" >> $DOCKERME_LOG.log
+		fi
+	  progress_step
+	done
 }
 DOCKERME_CONTAINERS_BACKUP_LIST(){
 	DOCKERME_IF_WEBSITE_DIRECTORY_NOT_EXIST
@@ -981,8 +1043,10 @@ elif [[ " $1 " = *"-c"* ]] && [[ -n "$2" ]] && [[ -n "$3" ]] && [[ -z "$4" ]]; t
  	DOMAINE_NAME=$2 YML=$3 DOCKERME_CONTAINERS_CREATE
 elif [[ " $1 " = *"-b"* ]] && [[ -n "$2" ]] && [[ -z "$3" ]]; then
  	DOMAINE_NAME=$2 DOCKERME_CONTAINERS_BACKUP
-elif [[ " $1 " = *"-b"* ]] && [[ "$2" ]] && [[ "$3" = *"--list"* ]] && [[ -z "$4" ]]; then
- 	DOMAINE_NAME=$2 DOCKERME_CONTAINERS_BACKUP_LIST
+elif [[ " $1 " = *"-b"* ]] && [[ -n "$2" ]] && [[ -z "$3" ]]; then
+ 	DOMAINE_NAME=$2 DOCKERME_CONTAINERS_BACKUP
+elif [[ " $1 " = *"-b"* ]] && [[ "$2" ]] && [[ "$3" = *"--older"* ]] && [[ "$4" ]] && [[ -z "$5" ]]; then
+	DOMAINE_NAME=$2 OLDER_THAN_N_DAYS=$4 DOCKERME_CONTAINERS_BACKUP_DELETE_OLD
 #elif [[ " $1 " = *"-b"* ]] && [[ "$2" = *"-s"* ]] && [[ -n "$3" ]] && [[ -z "$4" ]]; then
 # 	echo "DOCKERME_BACKUPS_SCHADULED not uplemented yed!"
 #elif [[ " $1 " = *"-b"* ]] && [[ "$2" = *"-s"* ]] && [[ -n "$3" ]] && [[ -z "$4" ]]; then
