add function vew log

diff --git a/dockerme b/dockerme
--- a/dockerme
+++ b/dockerme
@@ -696,6 +696,14 @@ DOCKERME_CREATE_CONTAINERS(){
 		progress_step
 	done
 }
+DOCKERME_LOG_VIEW(){
+	DOCKERME_IF_DOCKERME_INSTALLED
+	tail -f $DOCKERME_LOG.log
+	if [[ ! $? -eq 0 ]]; then
+		echo " * WIEW LOG............................................................................................................[FAIL]"
+		echo $d `users` ": [FAIL] : VIEWING LOG : CODE VL01" >> $DOCKERME_LOG.log	
+	fi	
+}
 DOCKERME_HEADER
 DOCKERME_GLOBAL_VARS
-DOMAINE_NAME=ayoub.tn YML=wordpress4.9.5-php7.0-apache_mysql5.7.22 DOCKERME_CREATE_CONTAINERS
+#DOMAINE_NAME=ayoub.tn YML=wordpress4.9.5-php7.0-apache_mysql5.7.22 DOCKERME_CREATE_CONTAINERS
