add DOCKERME_IF_WEBSITE_DIRECTORY_NOT_EXIST

diff --git a/dockerme b/dockerme
--- a/dockerme
+++ b/dockerme
@@ -600,6 +600,15 @@ DOCKERME_IF_WEBSITE_DIRECTORY_EXIST(){
 		exit
 	fi
 }
+DOCKERME_IF_WEBSITE_DIRECTORY_NOT_EXIST(){
+	DOCKERME_IF_DOCKERME_INSTALLED
+	. /$DOCKERME_CONFIG
+	if [ ! -d $HOME_PATH_DIRECTORY/$DOMAINE_NAME ]; then
+		echo " * DOMAINE NAME NOT FOUND..........................................................................................[FAIL]"
+		echo $d `users` ": [FAIL] : DOMAINE NAME $DOMAINE_NAME NOT FOUND " >> $DOCKERME_LOG.log
+		exit
+	fi
+}
 DOCKERME_IF_YML_EXIST(){
 	DOCKERME_IF_DOCKERME_INSTALLED
 	if [ ! -f $DOCKERME_YML_DIRECTORY/$1 ]; then
@@ -615,7 +624,33 @@ DOCKERME_IF_NGINX-PROXY_EXIST(){
 		echo $d `users` ": [FAIL] : NGINX-PROXY CONTAINER NOT FOUND" >> $DOCKERME_LOG.log
 		exit
 	fi
-} 
+}
+DOCKERME_CONTAINERS_STOP(){
+	DOMAINE_NAME=$DOMAINE_NAME DOCKERME_IF_WEBSITE_DIRECTORY_NOT_EXIST
+	. /$DOCKERME_CONFIG
+	cd $HOME_PATH_DIRECTORY/$DOMAINE_NAME 1>/dev/null 2>&1;
+	docker-compose down 1>/dev/null 2>&1;
+	if [[ $? -eq 0 ]]; then
+		echo " * STOP CONTAINERS.....................................................................................................[OK]"
+		echo $d `users` ": [OK] : STOP CONTAINERS FOR $DOMAINE_NAME" >> $DOCKERME_LOG.log
+	else
+		echo " * STOPING CONTAINER...................................................................................................[FAIL]"
+		echo $d `users` ": [FAIL] : STOPING CONTAINERS FORM $DOMAINE_NAME : CODE CSTO01" >> $DOCKERME_LOG.log
+	fi
+}
+DOCKERME_CONTAINERS_START(){
+	DOMAINE_NAME=$DOMAINE_NAME DOCKERME_IF_WEBSITE_DIRECTORY_NOT_EXIST
+	. /$DOCKERME_CONFIG
+	cd $HOME_PATH_DIRECTORY/$DOMAINE_NAME 1>/dev/null 2>&1;
+	docker-compose up -d 1>/dev/null 2>&1;
+	if [[ $? -eq 0 ]]; then
+		echo " * START CONTAINERS....................................................................................................[OK]"
+		echo $d `users` ": [OK] : STARTING CONTAINERS FOR $DOMAINE_NAME" >> $DOCKERME_LOG.log
+	else
+		echo " * STARTING CONTAINER...................................................................................................[FAIL]"
+		echo $d `users` ": [FAIL] : STARTING CONTAINERS FORM $DOMAINE_NAME : CODE CSTA01" >> $DOCKERME_LOG.log
+	fi
+}
 DOCKERME_CONTAINERS_CREATE(){
 	PROGRESS_STICKY=yes
 	PROGRESS_WIDTH=100
@@ -717,33 +752,46 @@ DOCKERME_CONTAINERS_CREATE(){
 		progress_step
 	done
 }
-DOCKERME_CONTAINERS_STOP(){
-	DOMAINE_NAME=$DOMAINE_NAME DOCKERME_IF_WEBSITE_DIRECTORY_EXIST
-	. /$DOCKERME_CONFIG
-	cd $HOME_PATH_DIRECTORY/$DOMAINE_NAME 1>/dev/null 2>&1;
-	docker-compose down 1>/dev/null 2>&1;
-	if [[ $? -eq 0 ]]; then
-		echo " * STOP CONTAINERS.....................................................................................................[OK]"
-		echo $d `users` ": [OK] : STOP CONTAINERS FOR $DOMAINE_NAME" >> $DOCKERME_LOG.log
-	else
-		echo " * STOPING CONTAINER...................................................................................................[FAIL]"
-		echo $d `users` ": [FAIL] : STOPING CONTAINERS FORM $DOMAINE_NAME : CODE CSTO01" >> $DOCKERME_LOG.log
-	fi
-}
-DOCKERME_CONTAINERS_START(){
-	DOMAINE_NAME=$DOMAINE_NAME DOCKERME_IF_WEBSITE_DIRECTORY_EXIST
-	. /$DOCKERME_CONFIG
-	cd $HOME_PATH_DIRECTORY/$DOMAINE_NAME 1>/dev/null 2>&1;
-	docker-compose up -d 1>/dev/null 2>&1;
-	if [[ $? -eq 0 ]]; then
-		echo " * START CONTAINERS....................................................................................................[OK]"
-		echo $d `users` ": [OK] : STARTING CONTAINERS FOR $DOMAINE_NAME" >> $DOCKERME_LOG.log
-	else
-		echo " * STARTING CONTAINER...................................................................................................[FAIL]"
-		echo $d `users` ": [FAIL] : STARTING CONTAINERS FORM $DOMAINE_NAME : CODE CSTA01" >> $DOCKERME_LOG.log
-	fi
+DOCKERME_CONTAINERS_REMOVE(){
+	PROGRESS_STICKY=yes
+	PROGRESS_WIDTH=100
+	PROGRESS_NUMBER_OF_STEPS=${1:-11}
+	progress_line_number=1
+	DOCKERME_PROGRESS
+	for i in $(seq $PROGRESS_NUMBER_OF_STEPS); do
+		if [[ $i -eq 1 ]]; then
+			echo " * REMOVE CONTAINERS...................................................................................................[INITIALIZING]"
+			echo $d `users` ": [INITIALIZING] : REMOVING CONTAINERS" >> $DOCKERME_LOG.log
+		elif [[ $i -eq 2 ]]; then
+			DOCKERME_IF_NGINX-PROXY_EXIST
+			echo " * CHECK NGINX-PROXY CONTAINER.........................................................................................[OK]"
+			echo $d `users` ": [OK] : CHEKING NGINX-PROXY CONTAINER" >> $DOCKERME_LOG.log
+		elif [[ $i -eq 3 ]]; then
+			DOMAINE_NAME=$DOMAINE_NAME DOCKERME_CONTAINERS_STOP
+		elif [[ $i -eq 4 ]]; then
+			sudo rm -r $HOME_PATH_DIRECTORY/$DOMAINE_NAME
+			if [[ $? -eq 0 ]]; then
+				echo " * DELETE HOME DIRECTORY...............................................................................................[OK]"
+				echo $d `users` ": [OK] : DELETING HOME DIRECTORY FOR $DOMAINE_NAME" >> $DOCKERME_LOG.log
+			else
+				echo " * DELETING HOME DIRECTORY.............................................................................................[FAIL]"
+				echo $d `users` ": [FAIL] : DELETING HOME DIRECTORY FOR $DOMAINE_NAME : CODE CR01" >> $DOCKERME_LOG.log
+				exit
+			fi
+		elif [[ $i -eq 11 ]]; then
+			echo " * REMOVE CONTAINERS...................................................................................................[COMPLETED]"
+			echo $d `users` ": [COMPLETED] : REMOVING CONTAINERS FOR $DOMAINE_NAME" >> $DOCKERME_LOG.log
+		fi
+		progress_step
+	done
 }
 DOCKERME_HEADER
 DOCKERME_GLOBAL_VARS
 #DOMAINE_NAME=ayoub.tn YML=wordpress4.9.5-php7.0-apache_mysql5.7.22 DOCKERME_CONTAINERS_CREATE
-DOMAINE_NAME=ayoub.tn DOCKERME_CONTAINERS_START
+#DOMAINE_NAME=ayoub.tn DOCKERME_CONTAINERS_START
+#DOMAINE_NAME=ayoub.tn DOCKERME_CONTAINERS_STOP
+#DOMAINE_NAME=ayoub.tn DOCKERME_CONTAINERS_REMOVE
+#DOMAINE_NAME=ayoub.tn DOCKERME_CONTAINERS_REMOVE
+
+
+
