update create function

diff --git a/dockerme b/dockerme
--- a/dockerme
+++ b/dockerme
@@ -603,81 +603,95 @@ DOCKERME_IF_NGINX-PROXY_EXIST(){
 DOCKERME_CREATE_CONTAINERS(){
 	PROGRESS_STICKY=yes
 	PROGRESS_WIDTH=100
-	PROGRESS_NUMBER_OF_STEPS=${1:-9}
+	PROGRESS_NUMBER_OF_STEPS=${1:-11}
 	progress_line_number=1
 	DOCKERME_PROGRESS
 	for i in $(seq $PROGRESS_NUMBER_OF_STEPS); do
 		if [[ $i -eq 1 ]]; then
-			echo " * CREATE CONTAINERS.................................................................................................[INITIALIZING]"
+			echo " * CREATE CONTAINERS...................................................................................................[INITIALIZING]"
 			echo $d `users` ": [INITIALIZING] : CREATING CONTAINERS" >> $DOCKERME_LOG.log
 		elif [[ $i -eq 2 ]]; then
 			DOCKERME_IF_NGINX-PROXY_EXIST
-			echo " * CHECK NGINX-PROXY CONTAINER.......................................................................................[OK]"
+			echo " * CHECK NGINX-PROXY CONTAINER.........................................................................................[OK]"
 			echo $d `users` ": [OK] : CHEKING NGINX-PROXY CONTAINER" >> $DOCKERME_LOG.log
 		elif [[ $i -eq 3 ]]; then
 			DOCKERME_IF_YML_EXIST $YML
-			echo " * CHECK YML FILE....................................................................................................[OK]"
+			echo " * CHECK YML FILE......................................................................................................[OK]"
 			echo $d `users` ": [OK] : CHEKING YML FILE $DOCKERME_YML_DIRECTORY/$YML" >> $DOCKERME_LOG.log
 		elif [[ $i -eq 4 ]]; then
 			DOCKERME_IF_WEBSITE_DIRECTORY_EXIST $DOMAINE_NAME
-			echo " * CHECK IF DOMAINE NAME NOT USED....................................................................................[OK]"
+			echo " * CHECK IF DOMAINE NAME NOT USED......................................................................................[OK]"
 			echo $d `users` ": [OK] : CHEKING IF DOMAINE NAME $DOMAINE_NAME NOT USED" >> $DOCKERME_LOG.log
 		elif [[ $i -eq 5 ]]; then
 			mkdir $HOME_PATH_DIRECTORY/$DOMAINE_NAME 1>/dev/null 2>&1;
 			if [[ $? -eq 0 ]]; then
-				echo " * CREATE HOME DIRECTORY.............................................................................................[OK]"
+				echo " * CREATE HOME DIRECTORY...............................................................................................[OK]"
 				echo $d `users` ": [OK] : CREATING HOME DIRECTORY $HOME_PATH_DIRECTORY/$DOMAINE_NAME" >> $DOCKERME_LOG.log
 			else
-				echo " * CREATING HOME DIRECTORY............................................................................................[FAIL]"
+				echo " * CREATING HOME DIRECTORY.............................................................................................[FAIL]"
 				echo $d `users` ": [FAIL] : CREATING HOME DIRECTORY $HOME_PATH_DIRECTORY/$DOMAINE_NAME : CODE CC05" >> $DOCKERME_LOG.log
 			fi
 		elif [[ $i -eq 6 ]]; then
 			touch $HOME_PATH_DIRECTORY/$DOMAINE_NAME/docker-compose.yml 1>/dev/null 2>&1;
 			if [[ $? -eq 0 ]]; then
-				echo " * CREATE docker-compose.yml AS EMPTY FILE...........................................................................[OK]"
+				echo " * CREATE DOCKER-COMPOSE.YML AS EMPTY FILE.............................................................................[OK]"
 				echo $d `users` ": [OK] : CREATING EMPTYFILE $HOME_PATH_DIRECTORY/$DOMAINE_NAME/docker-compose.yml" >> $DOCKERME_LOG.log
 			else
-				echo " * CREATING HOME DIRECTORY............................................................................................[FAIL]"
+				echo " * CREATE DOCKER-COMPOSE.YML AS EMPTY FILE.............................................................................[FAIL]"
 				echo $d `users` ": [FAIL] : CREATING EMPTYFILE $HOME_PATH_DIRECTORY/$DOMAINE_NAME/docker-compose.yml : CODE CC06" >> $DOCKERME_LOG.log
 			fi
 		elif [[ $i -eq 7 ]]; then
-			touch $HOME_PATH_DIRECTORY/$DOMAINE_NAME/docker-compose.yml 1>/dev/null 2>&1;
-			if [[ $? -eq 0 ]]; then
-				echo " * CREATE docker-compose.yml AS EMPTY FILE...........................................................................[OK]"
-				echo $d `users` ": [OK] : CREATING EMPTYFILE $HOME_PATH_DIRECTORY/$DOMAINE_NAME/docker-compose.yml" >> $DOCKERME_LOG.log
-			else
-				echo " * CREATING HOME DIRECTORY............................................................................................[FAIL]"
-				echo $d `users` ": [FAIL] : CREATING EMPTYFILE $HOME_PATH_DIRECTORY/$DOMAINE_NAME/docker-compose.yml : CODE CC07" >> $DOCKERME_LOG.log
-			fi
-		elif [[ $i -eq 8 ]]; then
 			cat $DOCKERME_YML_DIRECTORY/$YML > $HOME_PATH_DIRECTORY/$DOMAINE_NAME/docker-compose.yml
 			if [[ $? -eq 0 ]]; then
-				echo " * COPY YML FILE IN docker-compose.yml...............................................................................[OK]"
+				echo " * COPY YML FILE IN docker-compose.yml.................................................................................[OK]"
 				echo $d `users` ": [OK] : COPYING $YML INTO $HOME_PATH_DIRECTORY/$DOMAINE_NAME/docker-compose.yml" >> $DOCKERME_LOG.log
 			else
-				echo " * COPYING YML FILE IN docker-compose.yml.............................................................................[FAIL]"
-				echo $d `users` ": [FAIL] : COPYING $YML INTO $HOME_PATH_DIRECTORY/$DOMAINE_NAME/docker-compose.yml : CODE CC08" >> $DOCKERME_LOG.log
+				echo " * COPYING YML FILE IN docker-compose.yml..............................................................................[FAIL]"
+				echo $d `users` ": [FAIL] : COPYING $YML INTO $HOME_PATH_DIRECTORY/$DOMAINE_NAME/docker-compose.yml : CODE CC07" >> $DOCKERME_LOG.log
 				exit
 			fi
-		elif [[ $i -eq 9 ]]; then
+		elif [[ $i -eq 8 ]]; then
 			cd $HOME_PATH_DIRECTORY/$DOMAINE_NAME
 			sudo sed -i -e  's/$host/'$DOMAINE_NAME'/g' docker-compose.yml 1>/dev/null 2>&1;
 			if [[ $? -eq 0 ]]; then
 				sudo sed -i -e 's|$path|'$HOME_PATH_DIRECTORY'|g' docker-compose.yml 1>/dev/null 2>&1;
 				if [[ $? -eq 0 ]]; then
-					echo " * COMPOSE docker-compose.yml........................................................................................[OK]"
+					echo " * COMPOSE docker-compose.yml..........................................................................................[OK]"
 					echo $d `users` ": [OK] : COMPOSE $YML INTO $HOME_PATH_DIRECTORY/$DOMAINE_NAME/docker-compose.yml" >> $DOCKERME_LOG.log
 				else
-					echo " * COMPOSING YML FILE................................................................................................[FAIL]"
-					echo $d `users` ": [FAIL] : COMPOSING YML FILE INTO $HOME_PATH_DIRECTORY/$DOMAINE_NAME/docker-compose.yml : CODE CC09" >> $DOCKERME_LOG.log
+					echo " * COMPOSING YML FILE..................................................................................................[FAIL]"
+					echo $d `users` ": [FAIL] : COMPOSING YML FILE INTO $HOME_PATH_DIRECTORY/$DOMAINE_NAME/docker-compose.yml : CODE CC08" >> $DOCKERME_LOG.log
 					exit
 				fi
 
 			else
-				echo " * COMPOSING YML FILE................................................................................................[FAIL]"
-				echo $d `users` ": [FAIL] : COMPOSING YML FILE INTO $HOME_PATH_DIRECTORY/$DOMAINE_NAME/docker-compose.yml : CODE CC09+" >> $DOCKERME_LOG.log
+				echo " * COMPOSING YML FILE..................................................................................................[FAIL]"
+				echo $d `users` ": [FAIL] : COMPOSING YML FILE INTO $HOME_PATH_DIRECTORY/$DOMAINE_NAME/docker-compose.yml : CODE CC08+" >> $DOCKERME_LOG.log
 				exit
 			fi
+		elif [[ $i -eq 9 ]]; then
+			docker-compose up -d 1>/dev/null 2>&1;
+			if [[ $? -eq 0 ]]; then
+				echo " * START CONTAINERS FROM LOCAL DOCKER-COMPOSE.YML......................................................................[OK]"
+				echo $d `users` ": [OK] : STARTING CONTAINERS FROM $HOME_PATH_DIRECTORY/$DOMAINE_NAME/docker-compose.yml" >> $DOCKERME_LOG.log
+			else
+				echo " * STARTING CONTAINERS FROM LOCAL DOCKER-COMPOSE.YML...................................................................[FAIL]"
+				echo $d `users` ": [FAIL] : STARTING CONTAINERS FROM $HOME_PATH_DIRECTORY/$DOMAINE_NAME/docker-compose.yml : CODE CC09" >> $DOCKERME_LOG.log
+				exit
+			fi
+		elif [[ $i -eq 10 ]]; then
+			docker container restart nginx-proxy 1>/dev/null 2>&1;
+			if [[ $? -eq 0 ]]; then
+				echo " * APPLICATE CONFIGURATION INSIDE NGINX-PROXY CONTAINER................................................................[OK]"
+				echo $d `users` ": [OK] : APPLICATING CONFIGURATION INSDE NGINX-PROXY CONTAINER FOR $DOMAINE_NAME" >> $DOCKERME_LOG.log
+			else
+				echo " * APPLICATING CONFIGURATION INSDE NGINX-PROXY CONTAINER...............................................................[FAIL]"
+				echo $d `users` ": [FAIL] : APPLICATING CONFIGURATION INSDE NGINX-PROXY CONTAINER FOR $DOMAINE_NAME : CODE CC10" >> $DOCKERME_LOG.log
+				exit
+			fi
+		elif [[ $i -eq 11 ]]; then
+			echo " * CREATE CONTAINERS...................................................................................................[COMPLETED]"
+			echo $d `users` ": [OK] : CREATE CONTAINERS FOR $DOMAINE_NAME" >> $DOCKERME_LOG.log
 		fi
 		progress_step
 	done
