add BACKUP_LIST && BACKUP_RESTORE

diff --git a/dockerme b/dockerme
--- a/dockerme
+++ b/dockerme
@@ -858,6 +858,88 @@ DOCKERME_CONTAINERS_BACKUP(){
 	  progress_step
 	done 
 }
+DOCKERME_CONTAINERS_BACKUP_LIST(){
+	DOCKERME_IF_WEBSITE_DIRECTORY_NOT_EXIST
+	ls -1 $HOME_PATH_DIRECTORY/$DOMAINE_NAME/backup 1>/dev/null 2>&1;
+	if [ $? -eq 0 ]; then
+		MESSAGES="BACKUPS LIST FOR $DOMAINE_NAME" STATUS=1 STATUS_MSG="INITIALIZING" DOCKERME_LOG_WRITE
+		echo ""
+		ls -1 $HOME_PATH_DIRECTORY/$DOMAINE_NAME/backup
+		echo ""
+		MESSAGES="BACKUPS LIST FOR $DOMAINE_NAME" STATUS=1 STATUS_MSG="COMPLETED" DOCKERME_LOG_WRITE
+		echo $d ": [OK] : BACKUPS LIST FOR $DOMAINE_NAME" >> $DOCKERME_LOG.log
+	else
+		MESSAGES="BACKUPS LIST FOR $DOMAINE_NAME" STATUS=1 STATUS_MSG="INITIALIZING" DOCKERME_LOG_WRITE
+		MESSAGES="BACKUP DIRECTORY NOT FOUND $DOMAINE_NAME" STATUS=0 STATUS_MSG="FAIL" DOCKERME_LOG_WRITE
+		echo $d ": [FAIL] : BACKUPS LIST FOR $DOMAINE_NAME" >> $DOCKERME_LOG.log
+		exit
+	fi
+}
+DOCKERME_CONTAINERS_BACKUP_RESTORE(){
+	PROGRESS_STICKY=yes
+	PROGRESS_WIDTH=100
+	progress_max_lines=1
+	PROGRESS_NUMBER_OF_STEPS=${1:-8}
+	DOCKERME_PROGRESS
+	for i in $(seq $PROGRESS_NUMBER_OF_STEPS); do
+		if [[ $i -eq 1 ]]; then
+			MESSAGES="RESTORE BACKUP FILE $BACKUP_FILE FOR DOMAINE $DOMAINE_NAME" STATUS=1 STATUS_MSG="INITIALIZING" DOCKERME_LOG_WRITE
+			echo $d ": [INITIALIZING] : RESTORING BACKUP FILE $BACKUP_FILE FOR DOMAINE $DOMAINE_NAME" >> $DOCKERME_LOG.log
+		elif [[ $i -eq 2 ]]; then
+			DOCKERME_IF_WEBSITE_DIRECTORY_NOT_EXIST
+			MESSAGES="CHECK DOMAINE_NAME $DOMAINE_NAME" STATUS=1 STATUS_MSG="OK" DOCKERME_LOG_WRITE
+		elif [[ $i -eq 3 ]]; then
+			if [ -f $HOME_PATH_DIRECTORY/$DOMAINE_NAME/backup/$BACKUP_FILE ]; then
+				MESSAGES="CHECK BACKUP FILE $BACKUP_FILE" STATUS=1 STATUS_MSG="OK" DOCKERME_LOG_WRITE
+			else
+				MESSAGES="CHECK BACKUP FILE $BACKUP_FILE" STATUS=0 STATUS_MSG="FAIL" DOCKERME_LOG_WRITE
+				exit
+			fi
+		elif [[ $i -eq 4 ]]; then
+			cd $HOME_PATH_DIRECTORY/$DOMAINE_NAME 1>/dev/null 2>&1;
+			shopt -s extglob 1>/dev/null 2>&1;
+			rm -r !(backup) 1>/dev/null 2>&1;
+			if [[ $? -eq 0 ]]; then
+				MESSAGES="REMOVE OLD FILES FROM $HOME_PATH_DIRECTORY/$DOMAINE_NAME" STATUS=1 STATUS_MSG="OK" DOCKERME_LOG_WRITE
+				echo $d ": [OK] : REMOVING OLD FILES FROM $HOME_PATH_DIRECTORY/$DOMAINE_NAME" >> $DOCKERME_LOG.log
+			else
+				MESSAGES="REMOVING OLD FILES" STATUS=0 STATUS_MSG="FAIL" DOCKERME_LOG_WRITE
+				echo $d ": [FAIL] : REMOVING OLD FILES FROM $HOME_PATH_DIRECTORY/$DOMAINE_NAME" >> $DOCKERME_LOG.log
+			fi
+		elif [[ $i -eq 5 ]]; then
+			cp $HOME_PATH_DIRECTORY/$DOMAINE_NAME/backup/$BACKUP_FILE $HOME_PATH_DIRECTORY/$DOMAINE_NAME/$BACKUP_FILE
+			if [[ $? -eq 0 ]]; then
+				MESSAGES="CREATE TEMPORARY BACKUP ARCHIVE FILE" STATUS=1 STATUS_MSG="OK" DOCKERME_LOG_WRITE
+				echo $d ": [OK] : CREATE TEMPORARY BACKUP ARCHIVE FILE" >> $DOCKERME_LOG.log
+			else
+				MESSAGES="CREATING TEMPORARY BACKUP ARCHIVE FILE" STATUS=0 STATUS_MSG="FAIL" DOCKERME_LOG_WRITE
+				echo $d ": [FAIL] : CREATING TEMPORARY BACKUP ARCHIVE FILE" >> $DOCKERME_LOG.log
+			fi
+		elif [[ $i -eq 6 ]]; then
+			unzip $BACKUP_FILE 1>/dev/null 2>&1;
+			if [[ $? -eq 0 ]]; then
+				MESSAGES="DECOMPRESS BACKUP ARCHIVE FILE" STATUS=1 STATUS_MSG="OK" DOCKERME_LOG_WRITE
+				echo $d ": [OK] : DECOMPRESSING BACKUP ARCHIVE FILE" >> $DOCKERME_LOG.log
+			else
+				MESSAGES="DECOMPRESSING TEMPORARY BACKUP ARCHIVE FILE" STATUS=0 STATUS_MSG="FAIL" DOCKERME_LOG_WRITE
+				echo $d ": [FAIL] : DECOMPRESSING BACKUP ARCHIVE FILE" >> $DOCKERME_LOG.log
+			fi
+		elif [[ $i -eq 7 ]]; then
+			rm $BACKUP_FILE 1>/dev/null 2>&1;
+			if [[ $? -eq 0 ]]; then
+				MESSAGES="REMOVE TEMPORARY BACKUP ARCHIVE FILE" STATUS=1 STATUS_MSG="OK" DOCKERME_LOG_WRITE
+				echo $d ": [OK] : REMOVING TEMPORARY BACKUP ARCHIVE FILE" >> $DOCKERME_LOG.log
+			else
+				MESSAGES="REMOVING TEMPORARY BACKUP ARCHIVE FILE" STATUS=0 STATUS_MSG="FAIL" DOCKERME_LOG_WRITE
+				echo $d ": [FAIL] : REMOVING TEMPORARY BACKUP ARCHIVE FILE" >> $DOCKERME_LOG.log
+			fi			
+		elif [[ $i -eq 8 ]]; then
+			MESSAGES="RESTORING BACKUP FILE $BACKUP_FILE FOR DOMAINE $DOMAINE_NAME" STATUS=1 STATUS_MSG="COMPLETED" DOCKERME_LOG_WRITE
+			echo $d ": [COMPLETED] : RESTORING BACKUP FILE $BACKUP_FILE FOR DOMAINE $DOMAINE_NAME" >> $DOCKERME_LOG.log
+		fi
+	  progress_step
+	done 
+}
 DOCKERME_HEADER
 DOCKERME_GLOBAL_VARS
 #DOCKERME_YML_LIST
@@ -869,4 +951,6 @@ DOCKERME_GLOBAL_VARS
 #DOMAINE_NAME=ayoub.tn DOCKERME_CONTAINERS_REMOVE
 #DOMAINE_NAME=ayoub.tn DOCKERME_CONTAINERS_START
 #DOMAINE_NAME=ayoub.tn DOCKERME_CONTAINERS_STOP
-DOMAINE_NAME=ayoub.tn DOCKERME_CONTAINERS_BACKUP
+#DOMAINE_NAME=ayoub.tn DOCKERME_CONTAINERS_BACKUP
+#DOMAINE_NAME=ayoub.tn DOCKERME_CONTAINERS_BACKUP_LIST
+#DOMAINE_NAME=ayoub.tn BACKUP_FILE=20180607095508.zip DOCKERME_CONTAINERS_BACKUP_RESTORE
