add delete entry from /etc/hosts

diff --git a/dockerme b/dockerme
--- a/dockerme
+++ b/dockerme
@@ -891,7 +891,7 @@ DOCKERME_CONTAINERS_CREATE_LOCAL(){
 DOCKERME_CONTAINERS_REMOVE(){
 	PROGRESS_STICKY=yes
 	PROGRESS_WIDTH=100
-	PROGRESS_NUMBER_OF_STEPS=${1:-5}
+	PROGRESS_NUMBER_OF_STEPS=${1:-6}
 	progress_line_number=1
 	DOCKERME_PROGRESS
 	for i in $(seq $PROGRESS_NUMBER_OF_STEPS); do
@@ -912,10 +912,19 @@ DOCKERME_CONTAINERS_REMOVE(){
 				echo $d ": [OK] : DELETING HOME DIRECTORY FOR $DOMAINE_NAME" >> $DOCKERME_LOG.log
 			else
 				MESSAGES="DELETING HOME DIRECTORY" STATUS=0 STATUS_MSG="FAIL" DOCKERME_LOG_WRITE
-				echo $d ": [FAIL] : DELETING HOME DIRECTORY FOR $DOMAINE_NAME : CODE CR01" >> $DOCKERME_LOG.log
+				echo $d ": [FAIL] : DELETING HOME DIRECTORY FOR $DOMAINE_NAME" >> $DOCKERME_LOG.log
 				exit
 			fi
 		elif [[ $i -eq 5 ]]; then
+			sudo sed -i "/$DOMAINE_NAME/ d" /etc/hosts
+			if [[ $? -eq 0 ]]; then
+				MESSAGES="REMOVE LOCL ENTRY FROM /ect/host" STATUS=1 STATUS_MSG="OK" DOCKERME_LOG_WRITE
+				echo $d ": [OK] : REMOVING LOCL ENTRY FROM /ect/host" >> $DOCKERME_LOG.log
+			else
+				MESSAGES="REMOVING LOCL ENTRY FROM /ect/host" STATUS=1 STATUS_MSG="WARNINIG" DOCKERME_LOG_WRITE
+				echo $d ": [WARNINIG] : REMOVING LOCL ENTRY FROM /ect/host" >> $DOCKERME_LOG.log
+			fi
+		elif [[ $i -eq 6 ]]; then
 			MESSAGES="REMOVE CONTAINERS" STATUS=1 STATUS_MSG="COMPLETED" DOCKERME_LOG_WRITE
 			echo $d ": [COMPLETED] : REMOVING CONTAINERS FOR $DOMAINE_NAME" >> $DOCKERME_LOG.log
 		fi
