making delete old backup independent function

diff --git a/dockerme b/dockerme
--- a/dockerme
+++ b/dockerme
@@ -850,15 +850,7 @@ DOCKERME_CONTAINERS_BACKUP(){
 		elif [[ $i -eq 7 ]]; then
 			DOMAINE_NAME=$DOMAINE_NAME DOCKERME_CONTAINERS_START
 		elif [[ $i -eq 8 ]]; then
-			find $HOME_PATH_DIRECTORY/$DOMAINE_NAME/* -mtime +7 -exec rm {} \; 1>/dev/null 2>&1;
-			if [[ $? -eq 0 ]]; then
-				MESSAGES="DELETE OLD BACKUPS" STATUS=1 STATUS_MSG="OK" DOCKERME_LOG_WRITE
-				echo $d ": [OK] : DELETE OLD BACKUPS" >> $DOCKERME_LOG.log
-			else
-				MESSAGES="DELETING OLD BACKUPS" STATUS=1 STATUS_MSG="WARNING" DOCKERME_LOG_WRITE
-				echo $d ": [FAIL] : DELETING OLD BACKUPS" >> $DOCKERME_LOG.log
-				exit
-			fi
+			DOMAINE_NAME=$DOMAINE_NAME OLDER_THAN_N_DAYS="7" DOCKERME_DELETE_OLD_BACKUP
 		elif [[ $i -eq 9 ]]; then
 			MESSAGES="BACKUP $DOMAINE_NAME" STATUS=1 STATUS_MSG="COMPLETED" DOCKERME_LOG_WRITE
 			echo $d ": [COMPLETED] : BACKUP $DOMAINE_NAME" >> $DOCKERME_LOG.log
@@ -955,6 +947,20 @@ DOCKERME_CONTAINERS_BACKUP_RESTORE(){
 		fi
 	  progress_step
 	done 
+}
+DOCKERME_DELETE_OLD_BACKUP(){
+	. /$DOCKERME_CONFIG
+	#DOMAINE_NAME
+	#OLDER_THAN_N_DAYS
+	find $HOME_PATH_DIRECTORY/$DOMAINE_NAME/* -mtime +7 -exec rm {} \; 1>/dev/null 2>&1;
+	if [[ $? -eq 0 ]]; then
+		MESSAGES="DELETE BACKUPS OLDER THAN $OLDER_THAN_N_DAYS FOR $DOMAINE_NAME" STATUS=1 STATUS_MSG="OK" DOCKERME_LOG_WRITE
+		echo $d ": [OK] : DELETE BACKUPS OLDER THAN $OLDER_THAN_N_DAYS FOR $DOMAINE_NAME" >> $DOCKERME_LOG.log
+	else
+		MESSAGES="DELETING BACKUPS OLDER THAN $OLDER_THAN_N_DAYS FOR $DOMAINE_NAME" STATUS=1 STATUS_MSG="WARNING" DOCKERME_LOG_WRITE
+		echo $d ": [FAIL] : DELETING BACKUPS OLDER THAN $OLDER_THAN_N_DAYS FOR $DOMAINE_NAME" >> $DOCKERME_LOG.log
+		exit
+	fi
 }
 clear
 DOCKERME_HEADER
